HikingGear/Controllers/CategoriesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HikingGear.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace HikingGear.Controllers 
{
  [Authorize]
  public class CategoriesController : Controller
  {
    private readonly HikingGearContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public CategoriesController(UserManager<ApplicationUser> userManager, HikingGearContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        var userCategories = _db.Categories.Where(entry => entry.User.Id == currentUser.Id).ToList();
        return View(userCategories);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Category category, int GearId)
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        category.User = currentUser;
        _db.Categories.Add(category);
        _db.SaveChanges();
        if (GearId != 0)
        {
            _db.CategoryGear.Add(new CategoryGear() { GearId = GearId, CategoryId = category.CategoryId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCategory = _db.Categories
          .Include(category => category.JoinEntities)
          .ThenInclude(join => join.Gear)
          .FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    public ActionResult Edit(int id)
    {
      var thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    [HttpPost]
    public ActionResult Edit(Category category)
    {
      _db.Entry(category).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      _db.Categories.Remove(thisCategory);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HikingGear/Controllers/GearResultsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HikingGear.Models;

namespace HikingGear.Controllers
{
  public class GearResultsController : Controller
  {
    public IActionResult Index()
    {
      var allGearResults = GearResult.GetGearResults();
      return View(allGearResults);
    }

    [HttpPost]
    public IActionResult Index(GearResult gearResult)
    {
      GearResult.Post(gearResult);
      return RedirectToAction("Index");
    }

    public IActionResult Details(int id)
    {
      var gearResult = GearResult.GetDetails(id);
      return View(gearResult);
    }

    public IActionResult Edit(int id)
    {
      var gearResult = GearResult.GetDetails(id);
      return View(gearResult);
    }

    [HttpPost]
    public IActionResult Details(int id, GearResult gearResult)
    {
      gearResult.GearResultId = id;
      GearResult.Put(gearResult);
      return RedirectToAction("Details", id);
    }

    public IActionResult Delete(int id)
    {
      GearResult.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

HikingGear/Controllers/GearsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HikingGear.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace HikingGear.Controllers
{
  [Authorize]
  public class GearsController : Controller
  {
    private readonly HikingGearContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public GearsController(UserManager<ApplicationUser> userManager, HikingGearContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        var userGears = _db.Gears.Where(entry => entry.User.Id == currentUser.Id).ToList();
        return View(userGears);
    }

    public ActionResult Create()
    {
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Gear gear, int CategoryId)
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        gear.User = currentUser;
        _db.Gears.Add(gear);
        _db.SaveChanges();
        if (CategoryId != 0)
        {
            _db.CategoryGear.Add(new CategoryGear() { CategoryId = CategoryId, GearId = gear.GearId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisGear = _db.Gears
          .Include(gear => gear.JoinEntities)
          .ThenInclude(join => join.Category)
          .FirstOrDefault(gear => gear.GearId == id);
      return View(thisGear);
    }

    public ActionResult Edit(int id)
    {
      var thisGear = _db.Gears.FirstOrDefault(gear => gear.GearId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisGear);
    }

    [HttpPost]
    public ActionResult Edit(Gear gear, int CategoryId)
    {
      if (CategoryId != 0)
      {
        _db.CategoryGear.Add(new CategoryGear() { CategoryId = CategoryId, GearId = gear.GearId });
      }
      _db.Entry(gear).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCategory(int id)
    {
      var thisGear = _db.Gears.FirstOrDefault(gear => gear.GearId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisGear);
    }

    [HttpPost]
    public ActionResult AddCategory(Gear gear, int CategoryId)
    {
      if (CategoryId != 0)
      {
        _db.CategoryGear.Add(new CategoryGear() { CategoryId = CategoryId, GearId = gear.GearId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisGear = _db.Gears.FirstOrDefault(gear => gear.GearId == id);
      return View(thisGear);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisGear = _db.Gears.FirstOrDefault(gear => gear.GearId == id);
      _db.Gears.Remove(thisGear);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteCategory(int joinId)
    {
      var joinEntry = _db.CategoryGear.FirstOrDefault(entry => entry.CategoryGearId == joinId);
      _db.CategoryGear.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HikingGear/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Gear Cave</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The Gear Cave</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Gear Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gears" asp-action="Index">Gear List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">Upcoming Trips</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="GearResults" asp-action="Index">Search New Gear</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark">
                             @if (User.Identity.IsAuthenticated)
                            {
                                 @using (Html.BeginForm("LogOff", "Account"))
                                 {
                                    <li class="nav-link text-dark"><input type="submit" class="nav-item" value="LogOff" /></li>
                                 }
                            } 
                            else
                            {
                                @Html.ActionLink("Register", "Register", null, null, new {@class="nav-link text-dark"})
                            }
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>